name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ../../Dockerfile
        push: true
        tags: be-ais
    - name: SSH into instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ${{ secrets.INSTANCE_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop be-ais || true
          docker rm be-ais || true
          docker pull be-ais
          docker run -d --name be-ais -p 3000:3000 be-ais
